//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.selections

import com.apollographql.apollo.api.CompiledField
import com.apollographql.apollo.api.CompiledSelection
import com.apollographql.apollo.api.list
import com.apollographql.apollo.api.notNull
import com.lahzouz.apollo.graphql.client.type.Author
import com.lahzouz.apollo.graphql.client.type.GraphQLString
import kotlin.collections.List

public object GetAuthorsQuerySelections {
  private val __authors: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  public val __root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "authors",
          type = Author.type.notNull().list().notNull()
        ).selections(__authors)
        .build()
      )
}
