//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.selections

import com.apollographql.apollo.api.CompiledField
import com.apollographql.apollo.api.CompiledSelection
import com.apollographql.apollo.api.list
import com.apollographql.apollo.api.notNull
import com.lahzouz.apollo.graphql.client.type.Author
import com.lahzouz.apollo.graphql.client.type.Book
import com.lahzouz.apollo.graphql.client.type.GraphQLString
import com.lahzouz.apollo.graphql.client.type.Long
import kotlin.collections.List

public object GetBooksQuerySelections {
  private val __author: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __books: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "id",
          type = Long.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "title",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "author",
          type = Author.type.notNull()
        ).selections(__author)
        .build()
      )

  public val __root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "books",
          type = Book.type.notNull().list().notNull()
        ).selections(__books)
        .build()
      )
}
