package com.lahzouz.java.graphql.client.tests

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import java.nio.file.Files
import java.nio.file.Paths
import kotlin.io.path.exists

class OperationManifestTest {
    @Test
    @DisplayName("Checks that operationManifest.json file has been generated and it's not empty")
    fun operationManifestTest() {
        val path = Paths.get("target/generated/operationOutput/apollo/books/operationOutput.json")

        assertTrue(path.exists(), "operationOutput.json was not generated by the plugin")
        assertTrue(Files.size(path) > 0, "File is empty")
    }
}
