//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.type

import com.apollographql.apollo.api.CustomScalarType

/**
 * Built-in String
 */
public class GraphQLString {
  public companion object {
    public val type: CustomScalarType = CustomScalarType("String", "kotlin.String")
  }
}
