//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.type

import com.apollographql.apollo.api.CustomScalarType

/**
 * Long type
 */
public class Long {
  public companion object {
    public val type: CustomScalarType = CustomScalarType("Long", "java.lang.Long")
  }
}
