//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.builder

import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.DataBuilder
import com.apollographql.apollo.api.DataBuilderDsl
import com.apollographql.apollo.api.DataBuilderFactory
import com.apollographql.apollo.api.DataBuilderScope
import com.apollographql.apollo.api.ExecutableDefinition
import com.apollographql.apollo.api.FakeResolver
import com.apollographql.apollo.api.buildData
import com.lahzouz.apollo.graphql.client.type.Author
import kotlin.String
import kotlin.Unit

@DataBuilderDsl
public class AuthorBuilder(
  customScalarAdapters: CustomScalarAdapters,
) : DataBuilder<AuthorMap>(customScalarAdapters) {
  init {
    __typename = "Author"
  }

  public var name: String by __fields

  override fun build(): AuthorMap = AuthorMap(__fields)

  public companion object : DataBuilderFactory<AuthorBuilder> {
    override fun newBuilder(customScalarAdapters: CustomScalarAdapters): AuthorBuilder = AuthorBuilder(customScalarAdapters)
  }
}

public fun DataBuilderScope.buildAuthor(block: AuthorBuilder.() -> Unit): AuthorMap = AuthorBuilder(customScalarAdapters)
.apply {
  __typename = "Author"
}.apply(block)
.build()

public fun <D : Author.Data> ExecutableDefinition<D>.Data(customScalarAdapters: CustomScalarAdapters = CustomScalarAdapters.Empty, block: AuthorBuilder.() -> Unit): D = buildData(
  ADAPTER,
  customScalarAdapters,
  AuthorBuilder(customScalarAdapters).apply(block).build(),
)

public fun <D : Author.Data> ExecutableDefinition<D>.Data(
  resolver: FakeResolver,
  customScalarAdapters: CustomScalarAdapters = CustomScalarAdapters.Empty,
  block: AuthorBuilder.() -> Unit = {},
): D = buildData(
  ADAPTER,
  customScalarAdapters,
  AuthorBuilder(customScalarAdapters).apply(block).build(),
  ROOT_FIELD.selections,
  "Author",
  resolver,
)
