//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.builder

import com.apollographql.apollo.api.DataMap
import kotlin.Any
import kotlin.String
import kotlin.collections.Map

public class AuthorMap(
  __fields: Map<String, Any?>,
) : DataMap(__fields)
