//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.builder

import com.apollographql.apollo.api.BuilderProperty
import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.DataBuilder
import com.apollographql.apollo.api.DataBuilderDsl
import com.apollographql.apollo.api.DataBuilderFactory
import com.apollographql.apollo.api.DataBuilderScope
import com.apollographql.apollo.api.ExecutableDefinition
import com.apollographql.apollo.api.FakeResolver
import com.apollographql.apollo.api.buildData
import com.lahzouz.apollo.graphql.client.type.Book
import kotlin.String
import kotlin.Unit
import com.lahzouz.apollo.graphql.client.type.Long as TypeLong
import java.lang.Long as LangLong

@DataBuilderDsl
public class BookBuilder(
  customScalarAdapters: CustomScalarAdapters,
) : DataBuilder<BookMap>(customScalarAdapters) {
  init {
    __typename = "Book"
  }

  public var title: String by __fields

  public var author: AuthorMap by __fields

  public var id: LangLong by
      BuilderProperty(customScalarAdapters.responseAdapterFor<LangLong>(TypeLong.type))

  override fun build(): BookMap = BookMap(__fields)

  public companion object : DataBuilderFactory<BookBuilder> {
    override fun newBuilder(customScalarAdapters: CustomScalarAdapters): BookBuilder = BookBuilder(customScalarAdapters)
  }
}

public fun DataBuilderScope.buildBook(block: BookBuilder.() -> Unit): BookMap = BookBuilder(customScalarAdapters)
.apply {
  __typename = "Book"
}.apply(block)
.build()

public fun <D : Book.Data> ExecutableDefinition<D>.Data(customScalarAdapters: CustomScalarAdapters = CustomScalarAdapters.Empty, block: BookBuilder.() -> Unit): D = buildData(
  ADAPTER,
  customScalarAdapters,
  BookBuilder(customScalarAdapters).apply(block).build(),
)

public fun <D : Book.Data> ExecutableDefinition<D>.Data(
  resolver: FakeResolver,
  customScalarAdapters: CustomScalarAdapters = CustomScalarAdapters.Empty,
  block: BookBuilder.() -> Unit = {},
): D = buildData(
  ADAPTER,
  customScalarAdapters,
  BookBuilder(customScalarAdapters).apply(block).build(),
  ROOT_FIELD.selections,
  "Book",
  resolver,
)
