//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client

import com.apollographql.apollo.annotations.ApolloAdaptableWith
import com.apollographql.apollo.api.Adapter
import com.apollographql.apollo.api.CompiledField
import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.ExecutableDefinition
import com.apollographql.apollo.api.Query
import com.apollographql.apollo.api.json.JsonWriter
import com.apollographql.apollo.api.obj
import com.lahzouz.apollo.graphql.client.adapter.GetBooksQuery_ResponseAdapter
import com.lahzouz.apollo.graphql.client.selections.GetBooksQuerySelections
import java.lang.Long
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import com.lahzouz.apollo.graphql.client.type.Query as CompiledQuery

public class GetBooksQuery() : Query<GetBooksQuery.Data> {
  override fun equals(other: Any?): Boolean = other != null && other::class == this::class

  override fun hashCode(): Int = this::class.hashCode()

  override fun id(): String = OPERATION_ID

  override fun document(): String = OPERATION_DOCUMENT

  override fun name(): String = OPERATION_NAME

  override fun serializeVariables(
    writer: JsonWriter,
    customScalarAdapters: CustomScalarAdapters,
    withDefaultValues: Boolean,
  ) {
    // This operation doesn't have any variable
  }

  override fun adapter(): Adapter<Data> = ADAPTER

  override fun rootField(): CompiledField = ROOT_FIELD

  @ApolloAdaptableWith(GetBooksQuery_ResponseAdapter.Data::class)
  public data class Data(
    public val books: List<Book>,
  ) : Query.Data

  public data class Book(
    public val id: Long,
    public val title: String,
    public val author: Author,
  )

  public data class Author(
    public val name: String,
  )

  public companion object : ExecutableDefinition<Data> {
    override val ADAPTER: Adapter<Data> = GetBooksQuery_ResponseAdapter.Data.obj()

    override val ROOT_FIELD: CompiledField = CompiledField.Builder(
          name = "data",
          type = CompiledQuery.type
        )
        .selections(selections = GetBooksQuerySelections.__root)
        .build()

    public const val OPERATION_ID: String =
        "4c33fd9fc50eee000565e2020e2cf5a02aff74b4ba2e132ea817a894ad79781b"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * ```
     * query GetBooks {
     *   books {
     *     id
     *     title
     *     author {
     *       name
     *     }
     *   }
     * }
     * ```
     */
    public val OPERATION_DOCUMENT: String
      get() = "query GetBooks { books { id title author { name } } }"

    public const val OPERATION_NAME: String = "GetBooks"
  }
}
