//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.adapter

import com.apollographql.apollo.api.Adapter
import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.StringAdapter
import com.apollographql.apollo.api.json.JsonReader
import com.apollographql.apollo.api.json.JsonWriter
import com.apollographql.apollo.api.list
import com.apollographql.apollo.api.missingField
import com.apollographql.apollo.api.obj
import com.lahzouz.apollo.graphql.client.GetAuthorsQuery
import kotlin.String
import kotlin.collections.List

public object GetAuthorsQuery_ResponseAdapter {
  public object Data : Adapter<GetAuthorsQuery.Data> {
    public val RESPONSE_NAMES: List<String> = listOf("authors")

    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): GetAuthorsQuery.Data {
      var _authors: List<GetAuthorsQuery.Author>? = null

      while (true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> _authors = Author.obj().list().fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return GetAuthorsQuery.Data(
        authors = _authors ?: missingField(reader, "authors")
      )
    }

    override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: GetAuthorsQuery.Data,
    ) {
      writer.name("authors")
      Author.obj().list().toJson(writer, customScalarAdapters, value.authors)
    }
  }

  public object Author : Adapter<GetAuthorsQuery.Author> {
    public val RESPONSE_NAMES: List<String> = listOf("name")

    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): GetAuthorsQuery.Author {
      var _name: String? = null

      while (true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> _name = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return GetAuthorsQuery.Author(
        name = _name ?: missingField(reader, "name")
      )
    }

    override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: GetAuthorsQuery.Author,
    ) {
      writer.name("name")
      StringAdapter.toJson(writer, customScalarAdapters, value.name)
    }
  }
}
