//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.adapter

import com.apollographql.apollo.api.Adapter
import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.StringAdapter
import com.apollographql.apollo.api.json.JsonReader
import com.apollographql.apollo.api.json.JsonWriter
import com.apollographql.apollo.api.list
import com.apollographql.apollo.api.missingField
import com.apollographql.apollo.api.obj
import com.lahzouz.apollo.graphql.client.GetBooksQuery
import kotlin.String
import kotlin.collections.List
import com.lahzouz.apollo.graphql.client.type.Long as TypeLong
import java.lang.Long as LangLong

public object GetBooksQuery_ResponseAdapter {
  public object Data : Adapter<GetBooksQuery.Data> {
    public val RESPONSE_NAMES: List<String> = listOf("books")

    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): GetBooksQuery.Data {
      var _books: List<GetBooksQuery.Book>? = null

      while (true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> _books = Book.obj().list().fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return GetBooksQuery.Data(
        books = _books ?: missingField(reader, "books")
      )
    }

    override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: GetBooksQuery.Data,
    ) {
      writer.name("books")
      Book.obj().list().toJson(writer, customScalarAdapters, value.books)
    }
  }

  public object Book : Adapter<GetBooksQuery.Book> {
    public val RESPONSE_NAMES: List<String> = listOf("id", "title", "author")

    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): GetBooksQuery.Book {
      var _id: LangLong? = null
      var _title: String? = null
      var _author: GetBooksQuery.Author? = null

      while (true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> _id = customScalarAdapters.responseAdapterFor<LangLong>(TypeLong.type).fromJson(reader, customScalarAdapters)
          1 -> _title = StringAdapter.fromJson(reader, customScalarAdapters)
          2 -> _author = Author.obj().fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return GetBooksQuery.Book(
        id = _id ?: missingField(reader, "id"),
        title = _title ?: missingField(reader, "title"),
        author = _author ?: missingField(reader, "author")
      )
    }

    override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: GetBooksQuery.Book,
    ) {
      writer.name("id")
      customScalarAdapters.responseAdapterFor<LangLong>(TypeLong.type).toJson(writer, customScalarAdapters, value.id)

      writer.name("title")
      StringAdapter.toJson(writer, customScalarAdapters, value.title)

      writer.name("author")
      Author.obj().toJson(writer, customScalarAdapters, value.author)
    }
  }

  public object Author : Adapter<GetBooksQuery.Author> {
    public val RESPONSE_NAMES: List<String> = listOf("name")

    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): GetBooksQuery.Author {
      var _name: String? = null

      while (true) {
        when (reader.selectName(RESPONSE_NAMES)) {
          0 -> _name = StringAdapter.fromJson(reader, customScalarAdapters)
          else -> break
        }
      }

      return GetBooksQuery.Author(
        name = _name ?: missingField(reader, "name")
      )
    }

    override fun toJson(
      writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters,
      `value`: GetBooksQuery.Author,
    ) {
      writer.name("name")
      StringAdapter.toJson(writer, customScalarAdapters, value.name)
    }
  }
}
