//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.builder.resolver

import com.apollographql.apollo.api.FakeResolverContext
import com.apollographql.apollo.api.StringAdapter
import com.apollographql.apollo.api.json.MapJsonWriter
import kotlin.Any
import kotlin.String
import com.lahzouz.apollo.graphql.client.type.Long as TypeLong
import java.lang.Long as LangLong

public fun FakeResolverContext.adaptToJson(`value`: Any): Any {
  val writer = MapJsonWriter()
  when(mergedField.type.rawType().name){
    "String" -> StringAdapter.toJson(writer, customScalarAdapters, value as String)
    "Long" -> customScalarAdapters.responseAdapterFor<LangLong>(TypeLong.type).toJson(writer, customScalarAdapters, value as LangLong)
    else -> return value
  }
  return writer.root()!!
}
