//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '5.0.1'.
//
package com.lahzouz.apollo.graphql.client.builder.resolver

import com.apollographql.apollo.api.BaseFakeResolver
import kotlin.String
import kotlin.collections.List
import kotlin.collections.Map

public open class DefaultFakeResolver : BaseFakeResolver(possibleTypes)

public val possibleTypes: Map<String, List<String>> = mapOf(
    )
